[package]
license=["Apache-2.0"]
keywords=["YAML", "Parser"]
org="nipunayf"
name="yaml"
icon = "icon.png"
distribution = "2201.0.0"
repository="https://github.com/nipunayf/ballerina-yaml"
authors=["Nipuna Fernando"]

[build-options]
observabilityIncluded = true
